name: hpp_calculator
description: Aplikasi sederhana untuk menghitung HPP (Harga Pokok Penjualan) khusus UMKM

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8

  # Input formatting
  intl: ^0.19.0

  # Local storage dan state management
  shared_preferences: ^2.3.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
